---
  - name: Add ipv6 to lo interface
    shell: ip -6 addr add 2001::1/64 dev lo
    ignore_errors: True

  - name: Supply wendelin software release
    shell: slapos supply https://lab.nexedi.cn/nexedi/slapos/raw/master/software/wendelin/software.cfg local_computer

  - name: create partition script
    copy: src=request-wendelin dest=/tmp/playbook-request-wendelin mode=700

  - name: Request Wendelin instance
    shell: cat /tmp/playbook-request-wendelin | slapos console 

  - name: Add startup script
    copy: src=wendelin-startup dest=/usr/local/bin/wendelin-startup mode=755

  - name: Add to rc.local
    lineinfile: 
      dest=/etc/rc.local insertbefore=BOF 
      line='bash /usr/local/bin/wendelin-startup &'
      state=present

  - name: Get slapos.playbook directory name
    shell: cd /tmp/tmpplaybookwendelin-standalone.*/slapos.playbook.git/playbook/; echo $(pwd)/
    register: tmp_dir

  - name: Check if /opt/slapos.playbook already exists
    stat: path=/opt/slapos.playbook/
    register: playbook_state

  - name: Copy slapos.playbook
    copy: src={{ tmp_dir.stdout }} dest=/opt/slapos.playbook/
    when: playbook_state.stat.exists == False
