  # easy_install module for ansible version on debian 8 cannot upgrade package
  - name: Install/Upgrade latest slapos.libnetworkcache 
    shell: pip install --upgrade slapos.libnetworkcache

  - name: Instal/Upgrade latest slapcache
    shell: pip install --upgrade slapcache
