# Installations on newest Ansible which supports succeeded

  - name: Make sure pip is installed
    shell: easy_install pip
    when: pip_installed is failed and pip3_installed is failed

  - name: Install/Upgrade latest slapos.libnetworkcache using pip
    shell: pip install --upgrade slapos.libnetworkcache
    when: pip_installed is succeeded
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: 1

  - name: Install/Upgrade latest slapcache using pip
    shell: pip install --upgrade slapcache
    when: pip_installed is succeeded
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: 1

  - name: Install/Upgrade latest slapos.libnetworkcache using pip3
    shell: pip3 install --upgrade slapos.libnetworkcache
    when: pip3_installed is succeeded
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: 1

  - name: Install/Upgrade latest slapcache using pip3
    shell: pip3 install --upgrade slapcache
    when: pip3_installed is succeeded
    environment:
      PIP_BREAK_SYSTEM_PACKAGES: 1
