# Installations on old Ansible where tests are filter like

  - name: Make sure pip is installed
    shell: easy_install pip
    when: pip_installed | failed and pip3_installed | failed

  - name: Install/Upgrade latest slapos.libnetworkcache using pip
    shell: pip install --upgrade slapos.libnetworkcache
    when: pip_installed | success

  - name: Install/Upgrade latest slapcache using pip
    shell: pip install --upgrade slapcache
    when: pip_installed | success

  - name: Install/Upgrade latest slapos.libnetworkcache using pip3
    shell: pip3 install --upgrade slapos.libnetworkcache
    when: pip3_installed | success

  - name: Install/Upgrade latest slapcache using pip3
    shell: pip3 install --upgrade slapcache
    when: pip3_installed | success
