- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - upgrader_playbook: vifib-upgrade.yml
    - extra_playbook: bbu.yml
    - repeat_until_success: True
    - playbook_report: True

  vars_files:
    - settings/vifib.yml
    - settings/slapos-master.yml
    - settings/bbu.yml

  roles:
    - bbu
