- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    software_release_url: https://lab.nexedi.com/nexedi/slapos/raw/1.0.254/software/erp5/software.cfg
    bt5_list: erp5_full_text_mroonga_catalog erp5_configurator_standard
    startup_playbook_id: erp5-standalone.yml
    playbook_name: erp5
    request_instance_template: request-erp5.j2
    request_frontend_template: request-erp5-frontend.j2
  roles:
    - standalone-shared
