- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    software_release_url: https://lab.node.vifib.com/nexedi/slapos/raw/1.0.20/software/erp5/software.cfg 
    startup_playbook_id: erp5-standalone.yml 
    playbook_name: erp5
    request_instance_template: request-erp5-cluster.j2

  roles:
    - standalone-shared
