- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/gnet.yml

  vars:
    - computer_name: noname

  vars_prompt:
    - name: "re6sttoken"
      prompt: "\n\n
You are using the re6st automatic installer for FREE network.
\n\n

Your token
"
      private: no 
      default: "notoken"

    - name: "location"
      prompt: 'Manually enter your location (ignore if you want it detected automatically, format is "country code,continent code", e.g. "FR,EU")'
      private: no
      default: ""

    - name: "enable_router_advertisement"
      prompt: "Enable Router Advertisement"
      private: no
      default: 'no'

  roles:
    - { role: re6stnet-install }
    - { role: re6stnet-ensure-running }
    - role: routeadv
      when: enable_router_advertisement == 'yes'
