- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/gnet.yml

  vars:
    - computer_name: noname

  vars_prompt:
    - name: "re6sttoken"
      prompt: "If you have re6st token if you have (ignore if you already have a configured re6st):"
      private: no 
      default: "notoken"

  roles:
    - re6stnet
