- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/gnet.yml

  vars:
    - computer_name: noname

  vars_prompt:
    - name: "re6sttoken"
      prompt: "\n\n
You are running the Grandenet Installer\n\n
Please insert your token from Grandenet to configure your computer.\n
If you don't have a token, please access http://www.grandenet.cn/en \n
and request one. \n\n
Move informations at http://www.grandenet.cn/en/documentation/user
\n\n

Your token
"
      private: no 
      default: "notoken"

  roles:
    - re6stnet
