- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - settings/imt.yml

  roles:
    - { role: imt-slapos, post_config: True, startup: True }
