- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/imt.yml

  vars_prompt:
    - name: "re6sttoken"
      prompt: "If you have re6st token if you have (ignore if you already have a configured re6st running):"
      private: no 
      default: "notoken"

    - name: "computer_name"
      prompt: "What is this computer name?  (ignore if you already have a configured re6st running):"
      private: no
      default: "noname"

  roles:
    - re6stnet
