- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/imt.yml

  roles:
    - prompt_computername
    - prompt_slapostoken
    - { role: imt-slapos, mount_directory: /virt }
    - { role: slapos, package_state: present }
    - { role: package, package_name: ntp, package_state: present }
    - { role: imt-slapos, post_config: True }
