- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  roles:
    - { role: vm-bootstrap, startup_playbook_id: imt-vm-bootstrap.yml } 
    - ntp
    - vm-cloudera-manager
