- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  roles:
    - { role: package, package_name: radvd, package_state: present }
    - { role: package, package_name: dnsmasq, package_state: present }


