- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - re6st_annon: False
    - computer_name: noname
    - re6st_fingerprint: nofingerprint

  vars_prompt:
    - name: "re6st_registry_url"
      prompt: "What is the url to the Re6st registry?"
      private: no
      default: "http://re6stnet.nexedi.com/"

    - name: "location"
      prompt: 'Manually enter your location (ignore if you want it detected automatically, format is "country code,continent code", e.g. "FR,EU")'
      private: no
      default: ""

    - name: "re6sttoken"
      prompt: "Please insert your re6stnet token:"
      private: no 
      default: "notoken"

  roles:
    - { role: re6stnet-install }
    - { role: re6stnet-ensure-running }

