- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - re6st_annon: False
    - computer_name: noname
    - re6st_fingerprint: "sha256:3dfbc7a2daaa34214c92e52d45edf6056aa9cb4ad3b498f255f51609c1302de3"
    - re6st_registry_url: "https://re6st-registry.nxdcdn.com/"

  vars_prompt:
    - name: "location"
      prompt: 'Manually enter your location (ignore if you want it detected automatically, format is "country code,continent code", e.g. "FR,EU")'
      private: no
      default: ""

    - name: "re6sttoken"
      prompt: "Please insert your re6stnet token:"
      private: no 
      default: "notoken"

  roles:
    - { role: re6stnet-install }
    - { role: re6stnet-ensure-running }

