- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - computer_name: noname
    - slapostoken: notoken

  vars_files:
    - settings/vifib.yml

  roles:
    - {role: re6stnet-upgrader}
