- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/vifib.yml

  vars_prompt:
    - name: "computer_name"
      prompt: "What is this computer name?  (ignore if you already have a configured re6st and slapos):"
      private: no
      default: "noname"

  roles:
    - re6stnet-legacy
    - { role: package, package_name: ntp, package_state: present }

