- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/vifib.yml

  vars:
    interface_name: eth0

  roles:
    - prompt_computername
    - prompt_slapostoken
    - { role: slapos, package_state: present } 
    - { role: package, package_name: ntp, package_state: present }
    - vifib-team-ssh-key
