- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - computer_name: noname
    - slapostoken: notoken
    - interface_name: lo

  vars_files:
    - settings/vifib.yml
    - settings/slapos-master.yml

  roles:
    - { role: slapos, package_state: present } 
