# This playbook will install slapos-node package and then slapproxy (with the
# "slapos configure local" command line). The combination of a slapnode and a
# slapproxy is a slapos standalone.

- name: SlapOS Standalone
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Send the message to tell the test is success
      command: echo "Build successful, connect to"

  roles:
    - slapos-proxy
