# This playbook will install slapos-node package and then slapproxy (with the
# "slapos configure local" command line). The combination of a slapnode and a
# slapproxy is a slapos standalone.

- name: SlapOS Standalone
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Send the message to tell the test is success
      command: echo "Build successful, connect to:"
      register: build_msg

    - name: expose build message
      debug:
        msg="{{ build_msg }}"

  roles:
    - slapos-proxy
