- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: "slapos_master_url"
      prompt: "What is the url to the SlapOS Master API?  (ignore if you already have a configured re6st and slapos):"
      private: no
      default: "https://slap.vifib.com/"

    - name: "slapos_web_master_url"
      prompt: "What is the url to the SlapOS Master Website?  (ignore if you already have a configured re6st and slapos):"
      private: no
      default: "https://slapos.vifib.com/"

    - name: "register_computer"
      prompt: "Do you want to register your computer to SlapOS Master? (yes/no)"
      private: no
      default: "no"

  pre_tasks:
    - pause:
        prompt: "Name your computer (ignore if you already have a configured re6st and slapos) [noname]"
      when: register_computer == "yes"
      register: prompt
    - set_fact:
        computer_name: "{{ prompt.user_input | default('noname', true) }}"

    - pause:
        prompt: "Input your slapos token (ignore if you already have a configured slapos) [notoken]"
      when: computer_name != "noname"
      register: prompt
    - set_fact:
        slapostoken: "{{ prompt.user_input | default('notoken', true) }}" 

    - pause:
        prompt: "Which network interface are you using? (ignore if you already have a configured re6st) [lo]"
      when: slapostoken != "notoken"
      register: prompt
    - set_fact:
        interface_name: "{{ prompt.user_input | default('lo', true) }}" 

  roles:
    - { role: slapos, package_state: present }


