# This playbook will install slapos-node package and then slapproxy (with the
# "slapos configure local" command line). The combination of a slapnode and a
# slapproxy is a slapos standalone.

- name: SlapOS Standalone
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Send the message to tell the test is success
      command: echo "Build successful, connect to:"
      register: build_msg

    - name: expose build message
      debug:
        msg="{{ build_msg }}"
        
    - name: Allow loopback
      iptables:
        action: insert
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow DNS
      iptables:
        action: append
        chain: OUTPUT
        protocol: udp
        destination_port: 53
        jump: ACCEPT

    - name: Allow to use localhost
      iptables:
        action: append
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow to use localhost
      iptables:
        action: append
        chain: INPUT
        source: 127.0.0.1
        destination: 127.0.0.1
        jump: ACCEPT

    - name: Allow to use localhost
      iptables:
        action: append
        chain: OUTPUT
        source: 127.0.0.1
        destination: 127.0.0.1
        jump: ACCEPT

    - name: Allow to use 10.0.2.100
      iptables:
        action: append
        chain: INPUT
        source: 10.0.2.100
        destination: 10.0.2.100
        jump: ACCEPT

    - name: Allow to use 10.0.2.100
      iptables:
        action: append
        chain: OUTPUT
        source: 10.0.2.100
        destination: 10.0.2.100
        jump: ACCEPT

    - name: Allow to access shacache
      iptables:
        action: append
        chain: OUTPUT
        protocol: tcp
        destination: shacache.org
        destination_port: 80
        jump: ACCEPT

    - name: Allow the inbound connection started by us
      iptables:
        action: append
        chain: INPUT
        match: conntrack
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT


  roles:
    - slapos-proxy
