- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - upgrader_playbook: vifib-upgrade.yml
    - computer_name: noname
    - slapostoken: notoken

  vars_files:
    - settings/vifib.yml
    - settings/upgrader.yml
    - settings/slapos-master.yml

  roles:
    - { role: re6stnet, package_state: present }
    - { role: slapos, package_state: present } 
    - { role: package, package_name: ntp, package_state: present }
    - vifib-team-ssh-key
    - upgrader
    - vifib-server
