- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_files:
    - settings/vifib.yml

  roles:
    - repository
    - ntp
    - { role: package, package_name: lm-sensors, package_state: latest }
    - { role: package, package_name: wget, package_state: latest }
    - { role: package, package_name: openssl, package_state: latest }
    - { role: package, package_name: ca-certificates, package_state: latest }
    - { role: package, package_name: openssh-server, package_state: latest }
    - { role: package, package_name: strace, package_state: latest }
    - { role: package, package_name: htop, package_state: latest }
    - { role: package, package_name: ioping, package_state: latest }
    - { role: package, package_name: exim4-base, package_state: absent }
    - { role: package, package_name: slapos-node, package_state: latest }
    - { role: package, package_name: re6st-node, package_state: latest }
    - re6stnet
    - vifib-team-ssh-key
    - vifib-server
    - rsyslogd
    - sysstat
