- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - computer_name: noname
    - slapostoken: notoken 

  vars_files:
    - settings/vifib.yml

  roles:
    - { role: package, package_name: ntp, package_state: latest }
    - { role: package, package_name: wget, package_state: latest }
    - { role: package, package_name: openssl, package_state: latest }
    - { role: package, package_name: ca-certificates, package_state: latest }
    - { role: package, package_name: openssh-server, package_state: latest }
    - { role: package, package_name: slapos-node, package_state: latest }
    - vifib-team-ssh-key

