- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - upgrader_playbook: vifib-upgrade.yml

  vars_files:
    - settings/vifib.yml
    - settings/upgrader.yml

  vars_prompt:
    - name: "computer_name"
      prompt: "What is this computer name?  (ignore if you already have a configured re6st and slapos):"
      private: no
      default: "noname"

    - name: "slapostoken"
      prompt: "If you have slapos token if you have (ignore if you already have a configured slapos):"
      private: no
      default: "notoken"

  roles:
    - { role: re6stnet-legacy, package_state: present }
    - { role: slapos, package_state: present } 
    - { role: package, package_name: ntp, package_state: present }
    - vifib-server
    - upgrader
