- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - upgrader_playbook: vifib-upgrade.yml

  vars_files:
    - settings/vifib.yml
    - settings/slapos-master.yml

  vars_prompt:
    - name: "computer_name"
      prompt: "What is this computer name?  (ignore if you already have a configured re6st and slapos):"
      private: no
      default: "noname"

  pre_tasks:
    - pause:
        prompt: "Input your slapos token (ignore if you already have a configured slapos) [notoken]"
      when: computer_name != "noname"
      register: prompt
    - set_fact:
        slapostoken: "{{ prompt.user_input | default('notoken', true) }}"

    - pause:
        prompt: "Which interface will provide IPv6? (ignore if you already have a configured re6st) [lo]"
      when: slapostoken != "notoken"
      register: prompt
    - set_fact:
        interface_name: "{{ prompt.user_input | default('lo', true) }}"

  roles:
    - { role: re6stnet-install, package_state: present }
    - { role: slapos, package_state: present } 
    - vifib-team-ssh-key
    - upgrader
    - vifib-server
