- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    software_release_url: https://lab.node.vifib.com/nexedi/slapos/raw/1.0.11/software/slaprunner/software.cfg
    startup_playbook_id: webrunner-standalone.yml
    playbook_name: webrunner
    request_instance_template: request-webrunner.j2
    request_frontend_template: request-slapos-master-frontend.j2
  roles:
    - standalone-shared
