- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    software_release_url: https://lab.node.vifib.com/nexedi/slapos/raw/1.0.12/software/wendelin/software.cfg
    startup_playbook_id: wendelin-standalone.yml
    playbook_name: wendelin
    request_instance_template: request-wendelin.j2

  roles:
    - standalone-shared