# Playbook to prepare Olimex board to run a MOD-ENV sensor and
# parse the tracked data to Fluentd

- import_playbook: wendelin-olimex-base.yml

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: "ipv6_address_iot_gateway"
      prompt: "What is the IPv6 address of the host where the data will be send to (IoT Gateway)?"
      private: no
    - name: "tag_name"
      prompt: "What is your tag name?\nYour tag name must consist of 2 part separated by .(dot). First part is the name of the sensor and must be the same as the reference of the Data Supply. The second part is the type of data (Data Product)."
      private: no
      default: "sensor_1.sample-environment-raw-data"
    - name: "fluentd_software_name"
      prompt: "What is the name of your Fluentd Software relase?"
      private: no
      default: "Fluentd software release"

  vars:
    fluentd_config: |
      <source> 
      @type exec
      tag {{ tag_name }}
      command python /usr/local/bin/custom_read_bme280.py 
      run_interval 1m 
      <parse> 
      keys pressure, humidity, temperature 
      </parse> 
      </source>
      <match {{ tag_name }}> 
      @type forward 
      <server>
      name myserver1 
      host {{ ipv6_address_iot_gateway }}
      </server> 
      </match>

  roles:
    - role: olimex-sensor
    - role: fluentd
