# Playbook to prepare Olimex board to run a MOD-ENV sensor and
# parse the tracked data to Fluentd

- import_playbook: wendelin-olimex-base.yml

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  roles:
    - role: olimex-sensor
