# Simply import both playbooks so that all variables can be set by the user
- import_playbook: re6stnet.yml
- import_playbook: slapos.yml

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  pre_tasks:
    - pause:
        prompt: "What is the reference of your computer (COMP-XXXX)?"
      register: prompt
    - set_fact:
        computer_id: "{{ prompt.user_input }}"

  tasks:
    - name: Check if client configuration exists already
      stat: path=/root/.slapos/slapos-client.cfg
      register: slapos_client_cfg

    - name: Configure SlapOS client
      block:
        - pause:
            prompt: "Please enter a token from your SlapOS account (Ignore if you already configured the SlapOS Client)."
          register: prompt

        - set_fact:
            slapos_user_token: "{{ prompt.user_input }}"

        - name: Configure SlapOS Client
          shell: slapos configure client --token {{ slapos_user_token }}

      when: slapos_client_cfg.stat.exists == False
