- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    software_release_url: https://lab.nexedi.com/nexedi/slapos/raw/1.0.372/software/wendelin/software.cfg
    bt5_list: erp5_full_text_myisam_catalog erp5_configurator_standard erp5_wendelin_configurator
    wcfs: true
    startup_playbook_id: wendelin-standalone.yml
    request_instance_template: request-erp5.j2
    request_frontend_template: request-erp5-frontend.j2
    playbook_name: wendelin
  roles:
    - standalone-shared
