# Playbook to prepare Olimex board to act as a IoT Gateway
# which sends data to a Wendelin instance

- import_playbook: wendelin-olimex-base.yml

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: "streamtool_uri"
      prompt: "What is the URL of your Wendelin instance? (e.g. https://softinstXXXX.host.vifib.net)"
      private: no

    - name: "tag_name"
      prompt: "What is your tag name?\nYour tag name must consist of 2 part separated by .(dot). First part is the name of the sensor and must be the same as the reference of the Data Supply. The second part is the type of data (Data Product)."
      private: no
      default: "sensor_1.sample-environment-raw-data"

    - name: "user_name"
      prompt: "What is the user name for your Wendelin instance?"
      private: no
      default: "zope"

    - name: "user_password"
      prompt: "What is the password for the user of your Wendelin instance?"
      private: yes

  vars:
    fluentd_config: |
      <source>
      @type forward
      port 24224
      bind ::0 
      </source>
      <match {{ tag_name }}>
      @type wendelin
      streamtool_uri {{ streamtool_uri }}/erp5/portal_ingestion_policies/default
      user {{ user_name }}
      password {{ user_password }}
      <buffer>
      flush_mode interval
      @type file
      path fluentd-buffer-file/
      flush_interval 1m
      </buffer>

  roles:
    - role: fluentd
