# Playbook to prepare Olimex board to act as a IoT Gateway
# which sends data to a Wendelin instance

- import_playbook: wendelin-olimex-base.yml

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
