- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    software_release_url: https://lab.nexedi.cn/nexedi/slapos/raw/1.0.1/software/wendelin/software.cfg

  roles:
    - wendelin-standalone
    - standalone-shared
