- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    software_release_url: https://lab.node.vifib.com/nexedi/slapos/raw/1.0.55/software/wendelin/software.cfg
    bt5_list: erp5_full_text_myisam_catalog erp5_configurator_standard erp5_wendelin_configurator
    startup_playbook_id: wendelin-standalone.yml
    playbook_name: wendelin
  roles:
    - standalone-shared
    - { role: package, package_name: socat, package_state: present }
