# Simply import both playbooks so that all variables can be set by the user
- import_playbook: re6stnet.yml
- import_playbook: slapos.yml
 
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  
  vars_prompt:
    - name: "slapos_user_token"
      prompt: "Please enter a token from your SlapOS account."
      private: no
  
  tasks:
    - name: Configure SlapOS Client
      shell: slapos configure client --token {{ slapos_user_token }}
