- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - re6st_annon: False
    - re6st_fingerprint: nofingerprint

  vars_prompt:
    - name: "re6st_registry_url"
      prompt: "What is the url to the Re6st registry? (Ignore if you are using a FREEFIB Token from rapid.space)"
      private: no
      default: "http://re6stnet.gnet.erp5.cn/"

    - name: "re6sttoken"
      prompt: "Please insert your re6stnet token:"
      private: no 
      default: "notoken"

    - name: "slapos_master_url"
      prompt: "What is the url to the SlapOS Master API?  (ignore if you already have a configured re6st and slapos):"
      private: no
      default: "https://slap.vifib.com/"

    - name: "slapos_web_master_url"
      prompt: "What is the url to the SlapOS Master Website?  (ignore if you already have a configured re6st and slapos):"
      private: no
      default: "https://panel.rapid.space/"

    - name: "computer_name"
      prompt: "Name your computer (ignore if you already have a configured re6st and slapos or if you don't want to register your computer to SlapOS Master):"
      private: no
      default: "noname"

  pre_tasks:
    - pause:
        prompt: "Input your slapos token (ignore if you already have a configured slapos) [notoken]"
      when: computer_name != "noname"
      register: prompt
    - set_fact:
        slapostoken: "{{ prompt.user_input | default('notoken', true) }}"

    - pause:
        prompt: "Which interface will provide IPv6? (ignore if you already have a configured re6st) [lo]"
      when: slapostoken != "notoken"
      register: prompt
    - set_fact:
        interface_name: "{{ prompt.user_input | default('lo', true) }}"

    - pause:
        prompt: "How many SlapOS computer partitions would you like? [10]"
      when: slapostoken != "notoken"
      register: prompt
    - set_fact:
        partition_number: "{{ prompt.user_input | default('10', true) }}"

  roles:
    - role: re6stnet-install
    - role: re6stnet-ensure-running
    - { role: slapos, package_state: present }
