# Playbook to prepare Olimex board to run a MOD-ENV sensor and
# parse the tracked data to Fluentd

- import_playbook: wendelin-olimex-base.yml

- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local

  vars:
    - iptables_rules: |
        # To send data to IoT-Gateway
          
        iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
          
        LISTEN_SENSOR_PORT=24224

        ip6tables -A OUTPUT -p tcp --dport $LISTEN_SENSOR_PORT -j ACCEPT
        ip6tables -A OUTPUT -p udp --dport $LISTEN_SENSOR_PORT -j ACCEPT

        ip6tables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

  roles:
    - role: olimex-board
    - role: olimex-sensor
