- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution (ansible_distribution)
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version (ansible_distribution_version)
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version (ansible_distribution_major_version)
    debug: msg="{{ ansible_distribution_major_version }}"
  - name: OS family (ansible_os_family)
    debug: msg="{{ ansible_os_family }}"
  - name: LSB (ansible_lsb)
    debug: msg="{{ ansible_lsb }}"
