---

  - stat: path=/opt/upgrader/last-backport
    register: last_backport

  - shell: echo 1 > /opt/upgrader/last-backport
    when: last_backport.stat.exists == False

  - name: Run 2024-01-08 backport
    include_tasks: 2024-01-08.yml
    when: 1704717268 > lookup('file', '/opt/upgrader/last-backport')|int

  - name: Run 2025-08-07 backport
    include_tasks: 2025-08-07.yml
    when: 1754561058 > lookup('file', '/opt/upgrader/last-backport')|int

  - shell: echo {{ ansible_date_time.epoch }} > /opt/upgrader/last-backport
    when: 1754561058 > lookup('file', '/opt/upgrader/last-backport')|int
