---
- name: Get CPUs list
  shell: find /sys/devices/system/cpu -type d -name 'cpu[0-9]*'
  register: cpus

- name: Check scaling governor exists for CPUs
  stat:
    path: '{{ item }}/cpufreq/scaling_governor'
  with_items: '{{ cpus.stdout_lines }}'
  register: scaling_governor_stat

- name: Check if CPUs are offine
  shell: grep -q 0 {{ item.item }}/online
  register: cpu_offline
  ignore_errors: yes
  with_items: '{{ scaling_governor_stat.results }}'
  when: item.stat.exists

- name: Set CPU Scaling Governor to {{ value }}
  shell: 'echo {{ value }} > {{ item.item.item }}/cpufreq/scaling_governor'
  with_items: '{{ cpu_offline.results }}'
  when: ('rc' in item) and (item.rc != 0)
