---
    - command: mktemp
      register: export_csv

    - name: Backup re6st certificates
      command: cp -r /etc/re6stnet /etc/re6stnet.back creates=/etc/re6stnet.back removes=/etc/re6stnet

    - apt: name=sqlite3 state=present update_cache=yes
      when: ansible_os_family == "Debian"

    - yum: name=sqlite state=present update_cache=yes
      when: ansible_os_family == "Centos" or ansible_os_family == "RedHat"

    - name: Dump cache
      shell: sqlite3 -noheader -csv /var/lib/re6stnet/peers.db "select * from peer;" > {{ export_csv.stdout }} removes=/var/lib/re6stnet/peers.db 

    - include: debian.yml
      when: ansible_os_family == "Debian"

    - include: rhel.yml
      when: ansible_os_family == "Centos" or ansible_os_family == "RedHat"

    - file: path=/var/lib/re6stnet owner=root group=root mode=0755 state=directory

    - copy: 
        src: re6st_db_create.sql
        dest: /tmp/
        owner: root
        group: root
        mode: 0644

    - name: Create new cache
      shell: sqlite3 /var/lib/re6stnet/cache.db < /tmp/re6st_db_create.sql && rm /tmp/re6st_db_create.sql

    - name: Fill new cache
      command: sqlite3 -noheader -csv /var/lib/re6stnet/cache.db ".import {{ export_csv.stdout }} peer" 

    - name: Restart re6stnet service
      service: name=re6stnet enabled=yes state=restarted

    - command: rm {{ export_csv.stdout }}
