# Important note regarding frontend_software_release_url
# Please do not change the defined software release here, as only some
# versions of the software are known to be working.
# If the change is needed, then one needs to manually:
#  * assure that apache-frontend can be correctly installed (w/o shared)
#  * assure that apache-frontend can be instantiated with parameters similar
#    to ones used in the playbooks
#  * release new version
#  * upload it to binary cache
#  * then change here
frontend_software_release_url: https://lab.nexedi.com/nexedi/slapos/raw/1.0.135.1/software/apache-frontend/software.cfg
firewall_setup_template: setup-firewall.j2
frontend_master_reference: master-frn-{{ playbook_name }}
frontend_slave_reference: slave-srn-{{ playbook_name }}
backend_instance_reference: instance-of-{{ playbook_name }}
backend_url_path: /tmp/playbook-{{ playbook_name }}-backend-url
public_ipv4_path: /tmp/playbook-{{ playbook_name }}-public_ipv4
frontend_custom_domain: "{{ ansible_default_ipv4.address }}"
frontend_server_alias: "*"
frontend_ssl_crt_file: ""
frontend_ssl_key_file: ""
frontend_ssl_ca_crt_file: ""
