---
  - name: Install ntp
    apt: name=ntp state=latest update_cache=yes cache_valid_time=86400
    when: ansible_os_family == "Debian"

  - include: ../../yum/tasks/main.yml name=ntp cache_valid_time=86400
    when: ansible_os_family == "RedHat"

  - name: ensure ntp is runing
    service: name=ntp state=started enabled=yes
    when: ansible_os_family == "Debian"

  - name: check that system has timedatectl
    shell: timedatectl --version >/dev/null 2>&1
    register: timedatectl_exist
    ignore_errors: yes

  - name: enable synchronisation
    shell: timedatectl set-ntp true
    when: timedatectl_exist.rc == 0

  - name: ensure ntp is runing (RedHat)
    service: name=ntpd state=started enabled=yes
    when: ansible_os_family == "RedHat"
