---
  - name: Install ntp
    apt: name=ntp state=latest update_cache=no 
    when: ansible_os_family == "Debian"

  - name: Install ntp
    yum: name=ntp state=latest update_cache=no  
    when: ansible_os_family == "RedHat"

  - name: ensure ntp is runing
    service: name=ntp state=running enabled=yes
    when: ansible_os_family == "Debian"

  - name: ensure ntp is runing (RedHat)
    service: name=ntpd state=running enabled=yes
    when: ansible_os_family == "RedHat"
