---
  - name: Install ntp
    apt: name=ntp state=latest update_cache=yes cache_valid_time=86400
    when: ansible_os_family == "Debian"

  - include: ../../yum/tasks/main.yml name=ntp cache_valid_time=86400
    when: ansible_os_family == "RedHat"

  - name: ensure ntp is runing
    service: name=ntp state=running enabled=yes
    when: ansible_os_family == "Debian"

  - name: ensure ntp is runing (RedHat)
    service: name=ntpd state=running enabled=yes
    when: ansible_os_family == "RedHat"
