---
dependencies:
  - { role: package, package_name: ntp, package_state: present, when: ansible_distribution != "Fedora" or ansible_distribution_major_version|int < 34 }
  - { role: package, package_name: ntpsec, package_state: present, when: ansible_distribution == "Fedora" and ansible_distribution_major_version|int >= 34 }
