  - name: Install packages to scan
    shell: apt -y install {{ packages_to_scan }} || true

  - name: Create key and cert directory
    shell: mkdir -p {{ key_and_cert_dir }}

  - name: Create key and cert files
    # echo -e because the string contains "\n" characters
    shell: 'echo "{{ slapos_key }}" > {{ key_and_cert_dir }}/key; echo "{{ slapos_cert }}" > {{ key_and_cert_dir }}/certificate'

  - name: Create configuration from template
    shell: "sed '{{conf_regex}}' {{conf}}.in > {{conf}}"

  - name: Launch fluent-bit
    shell: "{{flb}} -e {{plugin}} -c {{conf}} &"
    # TODO: store fluent-bit's PID to wait for it at the end

  - name: Pre-scan
    shell: 'sleep 1; echo "{\"beginning_date\": \"{{ ansible_date_time.iso8601 }}\"}" >> {{log}}'

  - name: Scan /sbin
    shell: "{{mca}} /sbin {{log}}"

  - name: Scan /bin
    shell: "{{mca}} /bin {{log}}"

  - name: Post-scan
    shell: 'echo "{\"end_date\": \"{{ ansible_date_time.iso8601 }}\", \"end_marker\": \"fluentbit_end\"}" >> {{log}}'

  - name: Wait fluent-bit
    shell: 'waitpid $(pidof fluent-bit) || true'
    # pid not found: fluent-bit ended correctly before "pidof" is run

  - name: "Build successful, connect to:"
    shell: "true"
