  - name: Install packages to scan
    shell: apt -y install {{ packages_to_scan }} || true

  - name: Create configuration from template
    shell: "sed '{{conf_regex}}' {{conf}}.in > {{conf}}"

  - name: Launch fluent-bit
    shell: "{{flb}} -e {{plugin}} -c {{conf}} &"
    # TODO: store fluent-bit's PID to wait for it at the end

  - name: Pre-scan
    shell: "sleep 1"

  - name: Scan /sbin
    shell: "{{mca}} /sbin {{log}}"

  - name: Scan /bin
    shell: "{{mca}} /bin {{log}}"

  - name: Post-scan
    shell: 'echo "{end_marker: \"fluentbit_end\"}" >> {{log}}'

  - name: "Build successful, connect to:"
    shell: "true"
