  - name: Create configuration from template
    shell: "sed \"{{conf_regex}}\" {{mca_conf_path}}/flb.conf.in > {{mca_conf_path}}/flb.conf"

  - name: Scan directory
    shell: {{binary}} {{item}} {{flb}} {{flb_plugin}} {{flb_conf}} {{log}}
    with_items:
      - /sbin
      - /bin

  - name: Indicate success in the logs
    shell: "echo -e \"{{sucess_string}}\""
