
 - name: Add V SSH Key
   authorized_key: user=root key="{{ lookup('file', 'valentin_key') }}"

 - name: Add R SSH Key
   authorized_key: user=root key="{{ lookup('file', 'rafael_key') }}"

 - name: Add A SSH Key
   authorized_key: user=root key="{{ lookup('file', 'alain_key') }}"

 - name: Add N SSH Key
   authorized_key: user=root key="{{ lookup('file', 'nicolas_key') }}"

 - name: Add Y SSH Key
   authorized_key: user=root key="{{ lookup('file', 'yusei_key') }}"

 - name: Add T SSH Key
   authorized_key: user=root key="{{ lookup('file', 'tatuya_key') }}"

 - name: Add G SSH Key
   authorized_key: user=root key="{{ lookup('file', 'guillaume_key') }}"

 - name: Add TG SSH Key
   authorized_key: user=root key="{{ lookup('file', 'thomas_key') }}"

 - name: Add LNC SSH Key
   authorized_key: user=root key="{{ lookup('file', 'luke_chronos_key') }}"

 - name: Add LNW SSH Key
   authorized_key: user=root key="{{ lookup('file', 'luke_web_key') }}"

 - name: Add RC SSH Key
   authorized_key: user=root key="{{ lookup('file', 'romain_key') }}"

 - name: Add Jerome Perrin SSH Key
   authorized_key: user=root key="{{ lookup('file', 'jerome_perrin_key') }}"

 - name: Add Xiaowu Zhang SSH Key
   authorized_key: user=root key="{{ lookup('file', 'xiaowu_zhang_key') }}"

 - name: Add KW SSH Key
   authorized_key: user=root key="{{ lookup('file', 'klaus_key') }}"

 - name: Add KS SSH Key
   authorized_key: user=root key="{{ lookup('file', 'kazuhiko_key') }}"

 - name: Remove Hardik SSH Key
   authorized_key: user=root key="{{ lookup('file', 'remove_key_4') }}" state=absent

 - name: Remove VB SSH Key
   authorized_key: user=root key="{{ lookup('file', 'remove_key_3') }}" state=absent

 - name: Remove old G Key
   authorized_key: user=root key="{{ lookup('file', 'remove_key_2') }}" state=absent

 - name: Remove H Key
   authorized_key: user=root key="{{ lookup('file', 'remove_key_1') }}" state=absent

 - name: Remove C Key
   authorized_key: user=root key="{{ lookup('file', 'remove_key_0') }}" state=absent

