---
- name: Check if fstrim command exists
  stat:
    path: /sbin/fstrim
  register: fstrim

- name: Install cron for fstrim
  cron:
    name: fstrim
    job: /sbin/fstrim -a
    special_time: weekly
  when: fstrim.stat.exists
