---

  - name: Create /opt/upgrader where some logs will be stored
    file: path=/opt/upgrader state=directory mode=0755

# Amarisoft scripts

  - name: Create {{ amarisoft_dir }} directory
    file: path="{{ amarisoft_dir }}" state=directory mode=0755

  - name: Render get-amarisoft-info script
    template:
      src: get-amarisoft-info.j2
      dest: "{{ amarisoft_dir }}/get-amarisoft-info"
      mode: '0555'

  - name: Render get-license-info script for backwards compatibility
    template:
      src: get-amarisoft-info.j2
      dest: "{{ amarisoft_dir }}/get-license-info"
      mode: '0555'

  - name: Render init-sdr script
    template:
      src: init-sdr.j2
      dest: "{{ amarisoft_dir }}/init-sdr"
      mode: '0550'

  - name: Copy init-enb script
    copy: src=init-enb dest={{ amarisoft_dir }} owner=root mode=550

  - name: Copy init-mme script
    copy: src=init-mme dest={{ amarisoft_dir }} owner=root mode=550

  - name: Copy rm-tmp-lte script
    copy: src=rm-tmp-lte dest={{ amarisoft_dir }} owner=root mode=550

# Generate key

  - set_fact: cn="{{ ansible_hostname }}"

  - name: Create {{ pk_dir }} directory
    file: path="{{ pk_dir }}" state=directory mode=0755

  - stat: path="{{ pk_dir }}/{{ cn }}.key"
    register: private_key

  - name: Generate private key
    shell: 'openssl genrsa -out {{ pk_dir }}/{{ cn }}.key 4096'
    when: private_key.stat.exists == False

  - stat: path="{{ pk_dir }}/{{ cn }}.key"
    register: private_key

  - stat: path="{{ pk_dir }}/{{ cn }}.pub"
    register: public_key

  - name: Generate public key
    shell: 'openssl rsa -in {{ pk_dir }}/{{ cn }}.key -outform PEM -pubout -out {{ pk_dir }}/{{ cn }}.pub'
    when: private_key.stat.exists == True and public_key.stat.exists == False

# Amarisoft upgrade

  - name: Configure {{ amarisoft_dir }}/shacache.cfg
    copy: src=shacache.cfg dest={{ amarisoft_dir }}/shacache.cfg owner=root mode=644

  - name: Download Amarisoft
    script: download-amarisoft.py

  - name: Get Amarisoft version
    shell: '{{ amarisoft_dir }}/get-amarisoft-info -v'
    register: amarisoft_version

  - set_fact:
      amarisoft_path: "{{ amarisoft_dir }}/v{{ amarisoft_version.stdout }}"

# SSD image backports
#
  - stat: path="/opt/upgrader/playbook-tmp"
    register: playbook_tmp_dir

  - name: Do ors backport
    shell: ansible-playbook ors-image-backports.yml -i hosts 2>>/opt/upgrader/ors_backport.log  >> /opt/upgrader/ors_backport.log
    args:
      chdir: /opt/upgrader/playbook-tmp/
    when: playbook_tmp_dir.stat.exists == True

  - name: Do ors backport
    shell: ansible-playbook ors-image-backports.yml -i hosts 2>>/opt/upgrader/ors_backport.log  >> /opt/upgrader/ors_backport.log
    when: playbook_tmp_dir.stat.exists == False

# Radio Hardware

  - name: Create {{ sdr_dir }} directory
    file: path={{ sdr_dir }} state=directory mode=0755

  - name: Copy get-sdr-info script
    copy: src=get-sdr-info dest={{ sdr_dir }} owner=root mode=550

# Re6st

  - name: Configure re6st
    script: configure-re6st.py

# Slapos

  - name: Enable and start cron.service
    systemd: name=cron.service enabled=yes state=started

  - name: Configure slapos
    script: configure-slapos.py

  - name: Create {{ simpleran_dir }} directory
    file: path={{ simpleran_dir }} state=directory mode=0755

  - name: Copy format-ims script
    copy: src=format-ims dest={{ simpleran_dir }} owner=root mode=550

# Amarisoft software

  - name: Check if lteenb has capabilities
    shell: 'getcap {{ amarisoft_path }}/enb/lteenb | grep -q cap_sys_nice'
    ignore_errors: yes
    register: lteenb_cap

  - name: Set capabilities on lteenb
    shell: 'patchelf --set-rpath {{ amarisoft_path }}/enb {{ amarisoft_path }}/enb/lteenb && setcap cap_sys_nice=+pe {{ amarisoft_path }}/enb/lteenb'
    when: lteenb_cap.rc != 0

  - name: Check if lteenb-avx2 has capabilities
    shell: 'getcap {{ amarisoft_path }}/enb/lteenb-avx2 | grep -q cap_sys_nice'
    ignore_errors: yes
    register: lteenb_avx2_cap

  - name: Set capabilities on lteenb-avx2
    shell: 'patchelf --set-rpath {{ amarisoft_path }}/enb {{ amarisoft_path }}/enb/lteenb-avx2 && setcap cap_sys_nice=+pe {{ amarisoft_path }}/enb/lteenb-avx2'
    when: lteenb_avx2_cap.rc != 0

  - name: Check if lteims has capabilities
    shell: 'getcap {{ amarisoft_path }}/mme/lteims | grep cap_sys_admin | grep -q cap_net_raw'
    ignore_errors: yes
    register: lteims_cap

  - name: Set capabilities on lteims
    shell: 'patchelf --set-rpath {{ amarisoft_path }}/mme {{ amarisoft_path }}/mme/lteims && setcap cap_sys_admin,cap_net_raw=+pe {{ amarisoft_path }}/mme/lteims'
    when: lteims_cap.rc != 0

  - name: Create .amarisoft directory for SR
    file: path={{ amarisoft_dir }}/.amarisoft state=directory

  - name: Configure sudoers
    script: configure-sudoers {{ amarisoft_dir }} {{ amarisoft_version.stdout }} {{ sdr_dir }}

# Network

  - name: Configure firewall
    script: configure-firewall.py

  - name: Configure IPv4 forwarding
    lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.conf.all.forwarding=(.*)" line="net.ipv4.conf.all.forwarding=1" state=present

  - name: Configure IPv6 forwarding
    lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv6.conf.all.forwarding=(.*)" line="net.ipv6.conf.all.forwarding=1" state=present

  - name: Improve network stack behaviour (for core network)
    lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.tcp_congestion_control=(.*)" line="net.ipv4.tcp_congestion_control=bbr" state=present

  - name: Improve network stack behaviour (for core network)
    lineinfile: dest=/etc/sysctl.conf regexp="^net.core.rmem_max=(.*)" line="net.core.rmem_max=50000000" state=present

  - name: Improve network stack behaviour (for core network)
    lineinfile: dest=/etc/sysctl.conf regexp="^net.core.wmem_max=(.*)" line="net.core.wmem_max=5000000" state=present

  - name: Redirect 53 to 5353
    ansible.builtin.iptables:
      chain: PREROUTING
      table: nat
      protocol: udp
      match: udp
      jump: DNAT
      destination_port: '53'
      to_destination: ':5353'

  - name: Redirect 5353 to 53
    ansible.builtin.iptables:
      chain: POSTROUTING
      table: nat
      protocol: udp
      match: udp
      jump: SNAT
      source_port: '5353'
      to_source: ':53'

# System

  - name: Configure journald log size
    lineinfile: dest=/etc/systemd/journald.conf regexp="^SystemMaxUse=(.*)" line="SystemMaxUse=1G" state=present

  - name: Add kernel parameter
    script: configure-grub.py

# eNB performance

  - name: Disable ondemand service (changes CPU governor)
    systemd: name=ondemand.service enabled=no state=stopped
    ignore_errors: yes

# Schedule and upgrade playbook

  - name: Install upgrader
    shell: ansible-playbook upgrader-run.yml --extra-vars 'extra_playbook={{ extra_playbook }} upgrader_playbook={{ upgrader_playbook }} repeat_until_success={{ repeat_until_success }} upgrade_kernel={{ upgrade_kernel | default(False) == True }}' -i hosts 2>>/opt/upgrader/latest_daily_upgrade.log >> /opt/upgrader/latest_daily_upgrade.log
    when: launch_upgrader | bool

  - name: Add format-ims script to cron after slapos node boot
    lineinfile: dest=/etc/cron.d/slapos-node regexp="@reboot root /opt/slapos/bin/slapos node boot(.*)" line="@reboot root /opt/slapos/bin/slapos node boot >> /opt/slapos/log/slapos-node-format.log 2>&1 ; {{ simpleran_dir }}/format-ims {{ simpleran_dir }}/format-ims.log" state=present

  - name: Add format-ims script to cron after slapos node format
    lineinfile: dest=/etc/cron.d/slapos-node regexp="(.*)root /opt/slapos/bin/slapos node format(.*)" line="0 * * * * root /opt/slapos/bin/slapos node format >> /opt/slapos/log/slapos-node-format.log 2>&1 ; {{ simpleran_dir }}/format-ims {{ simpleran_dir }}/format-ims.log" state=present

  - name: Add format-ims script to cron every minute
    lineinfile: dest=/etc/cron.d/slapos-node regexp="(.*)root (\S*)/format-ims(.*)" line="* * * * * root {{ simpleran_dir }}/format-ims {{ simpleran_dir }}/format-ims.log" state=present

