  - name: Check if configuration exists already
    stat: path=/etc/opt/slapos/slapos.cfg
    register: slapos_cfg

  - name: Configure SlapOS with slapos node register
    shell: "slapos node register --token {{ slapostoken }} --master-url {{ slapos_master_url }} --master-url-web {{ slapos_web_master_url }} --interface-name {{ interface_name }} --partition-number {{ partition_number }} {{ computer_name }}"
    when: slapos_cfg.stat.exists == False and slapostoken != "notoken" and computer_name != "noname"

  - name: Check if configuration exists already
    stat: path=/etc/opt/slapos/slapos.cfg
    register: xslapos_cfg

  - name: Run slapos format for initial bootstrap
    shell: "slapos node format --now --alter_user=True"
    when: xslapos_cfg.stat.exists == True
