---
  - name: "Load acpi_cpufreq"
    shell: modprobe acpi_cpufreq > /dev/null  2>&1
  
  - name: "Load coretemp"
    shell: modprobe coretemp > /dev/null  2>&1
  
  - name: "Load f71882fg"
    shell: modprobe f71882fg > /dev/null  2>&1

  - name: "Do sysctl"
    shell: sysctl -w net.ipv4.neigh.default.gc_thresh1=512 net.ipv4.neigh.default.gc_thresh2=1024 net.ipv4.neigh.default.gc_thresh3=2048 net.ipv6.neigh.default.gc_thresh1=512 net.ipv6.neigh.default.gc_thresh2=1024 net.ipv6.neigh.default.gc_thresh3=2048
   
  - name: echo 1 > /sys/kernel/mm/ksm/run
    shell: echo 1 > /sys/kernel/mm/ksm/run

  - name: "Install firmware-realtek"
    apt: name=firmware-realtek
    apt: name=firmware-realtek state=latest update_cache=yes cache_valid_time=3600
    when: ansible_os_family == "Debian"
