#!/usr/bin/python3 -S
import glob, os, sys, tarfile, zipfile
d = "download-cache/dist"
p = "setuptools-*"
x, = glob.glob(d + "/" + p)
if x.endswith(".zip"):
    zipfile.ZipFile(x).extractall()
else:
    tarfile.TarFile.open(x, "r:*").extractall()
p = glob.glob(p)
sys.path.insert(0, os.path.abspath(p[0]))
from setuptools.command.easy_install import main
for x in "bin", "eggs":
    try:
        os.mkdir(x)
    except OSError as e:
        pass
main(["-f", d, "-mxd", x, "zc.buildout"])
p.append(*glob.glob("eggs/zc.buildout-*"))
with open(os.open("bin/buildout", os.O_CREAT|os.O_WRONLY|os.O_TRUNC, 0o777), "w") as f:
    f.write("""\
#!%s -S
import os, sys
d = os.path.dirname(os.path.abspath(os.path.realpath(__file__)))
d = os.path.dirname(d) + os.sep
sys.path[:0] = (%s)
from zc.buildout.buildout import main
sys.exit(main())
""" % (sys.executable, ", ".join("d + %r" % p for p in p)))
