#!/bin/bash
CONF="/etc/default/grub"
BAK="/tmp/default.grub"
cp $CONF $BAK;
if ! (grep -q idle=halt /etc/default/grub && grep -q nosmt=force /etc/default/grub); then
  set -x
  sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT.*\)idle=[a-z]* *\(.*\)/\1\2/g' $CONF;
  sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT.*\)"/\1 idle=halt"/g' $CONF;
  sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT.*\)maxcpus=[0-9]* *\(.*\)/\1\2/g' $CONF;
  sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT.*\)"/\1 nosmt=force"/g' $CONF;
  set +x
fi
if ! (grep -q idle=halt /proc/cmdline && grep -q nosmt=force /proc/cmdline); then
  if ! update-grub; then
    cp $BAK $CONF;
    update-grub;
  fi
fi
rm -f $BAK;
