#!/bin/bash
mkdir -p /etc/sudoers.d
PARTITION_AMOUNT="$(sed -n 's/partition_amount = \(.*\)/\1/gp' /etc/opt/slapos/slapos.cfg)"

add_line() {
  echo "Configuring /etc/sudoers.d/slapuser-$1..."/
  for i in $(seq 0 $(($PARTITION_AMOUNT-1))); do
    echo "slapuser$i ALL=NOPASSWD:$2" >> slapuser-20241205-$1
  done
  mv slapuser-20241205-$1 /etc/sudoers.d/
  chmod 440 /etc/sudoers.d/slapuser-20241205-$1
}
add_commands() {
  for c in "${@:2}"; do
    add_line $c $1/$c
  done
}

add_commands $1 rm-tmp-lte init-enb init-mme init-sdr
add_commands $3 get-sdr-info

c="sdr-util"
add_line $c "$1/$2/trx_sdr/sdr_util -c 0 version"
