#!/bin/bash
mkdir -p /etc/sudoers.d
PARTITION_AMOUNT="$(sed -n 's/partition_amount = \(.*\)/\1/gp' /etc/opt/slapos/slapos.cfg)"

add_line() {
  echo "Configuring /etc/sudoers.d/slapuser-$1..."/
  for i in $(seq 0 $(($PARTITION_AMOUNT-1))); do
    echo "slapuser$i ALL=NOPASSWD:$2" >> slapuser-$1
  done
  mv slapuser-$1 /etc/sudoers.d/
  chmod 440 /etc/sudoers.d/slapuser-$1
}
add_commands() {
  for c in "${@:2}"; do
    #SLAPUSER_LINES="$(cat /etc/sudoers.d/slapuser-$c 2> /dev/null | wc -l)"
    #if [ "$SLAPUSER_LINES" != "$PARTITION_AMOUNT" ]; then
    add_line $c $1/$c
    #fi
  done
}

add_commands $1 rm-tmp-lte init-enb init-mme init-sdr
add_commands $3 get-sdr-info

c="sdr-util"
SLAPUSER_LINES="$(cat /etc/sudoers.d/slapuser-$c 2> /dev/null | wc -l)"
if [ "$SLAPUSER_LINES" != "$PARTITION_AMOUNT" ]; then
  add_line $c "$1/$2/trx_sdr/sdr_util -c 0 version"
fi
