#!/bin/bash

OLD_AMARISOFT_PATH="/opt/amarisoft/$(ls -1 /opt/amarisoft | grep "^v2021-[0-9]\{2\}-[0-9]\{2\}$" | sort | tail -n1)"
AMARISOFT_PATH="/opt/amarisoft/$(ls -1 /opt/amarisoft | grep "^v[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$" | sort | tail -n1)"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

$AMARISOFT_PATH/trx_sdr/sdr_util version && exit;
lsof /dev/sdr0 && exit;
lsmod | grep -q sdr && rmmod sdr;
if echo $AMARISOFT_PATH | grep -v -q 2021; then
  cd $OLD_AMARISOFT_PATH/trx_sdr/kernel;
  make clean && make && bash init.sh;
  rmmod sdr;
fi
cd $AMARISOFT_PATH/trx_sdr/kernel;
make clean && make && bash init.sh;
