---

  - set_fact: cn="{{ ansible_hostname }}"

  - name: Update certificate signature list
    script: update-signature-list.py

  - name: Create directory if it does not exist
    file: path="{{ pkdir }}" state=directory mode=0755

  - stat: path="{{ pkdir }}/{{ cn }}.key"
    register: private_key

  - name: Generate private key
    shell: 'openssl genrsa -out {{ pkdir }}/{{ cn }}.key 4096'
    when: private_key.stat.exists == False

  - stat: path="{{ pkdir }}/{{ cn }}.key"
    register: private_key

  - stat: path="{{ pkdir }}/{{ cn }}.pub"
    register: public_key

  - name: Generate public key
    shell: 'openssl rsa -in {{ pkdir }}/{{ cn }}.key -outform PEM -pubout -out {{ pkdir }}/{{ cn }}.pub'
    when: private_key.stat.exists == True and public_key.stat.exists == False

  - name: Get monitor private directory path
    shell: 'realpath $(dirname $(grep -lR "software_release_url = .*software/monitor/software.cfg" $(find /srv/slapgrid -type f -name "buildout.cfg")))/srv/monitor/private'
    register: monitor_path

  - name: Create directory if it does not exist
    file: path="{{ monitor_path.stdout }}/playbook-report" state=directory mode=0755

  - stat: path="{{ pkdir }}/{{ cn }}.pub"
    register: public_key

  - name: Copy public key
    copy: src="{{ pkdir }}/{{ cn }}.pub" dest="{{ monitor_path.stdout }}/playbook-report/{{ cn }}.pub" owner=root mode=774
    when: public_key.stat.exists == True
