# Note: This file is unused, kept for explanation

# As https://unix.stackexchange.com/a/783712 states, forcing global
# is impossible, as Domains=~. works only if other interfaces are not
# configured, so we resort to direct edit of /etc/resolvconf/resolv.conf.d/base
[Resolve]
# Use unbound
DNS=127.0.0.1
# Force only this configuration
Domains=~.
DNSSEC=yes
DNSStubListener=no
