---
  #- include_tasks: "{{ ansible_distribution |lower }}.yml"
  - assert: { that: "ansible_distribution == 'Debian'" }
  - import_tasks: debian.yml

  #- command: "{{role_path}}/gen-ipcm-conf"
  - command: roles/rina/gen-ipcm-conf

  - service: name=ipcm-re6st enabled=yes
