#!/usr/bin/python3
import os, re, shutil, subprocess, sys, tarfile, tempfile
from functools import partial
from hashlib import sha512
from io import BytesIO
from urllib.request import urlopen
from debian.changelog import format_date, Changelog
from debian.deb822 import Deb822

# BBB: We want to support old OS that don't have
#      pybuild-plugin-pyproject/python3-hatchling
#      yet so the Python specific work is done while preparing the "source"
#      package for OBS. Which is acceptable anyway, because re6stnet is
#      pure-Python software and the result is similar to PyPI sdist tarballs.

REPOS = "https://lab.nexedi.com/nexedi/re6stnet"
# Can be increased temporarily when making a new release with the same revision
# for REPOS.
PKG_VERSION = 1
PACKAGE = "re6st-node"
PYOPENSSL = "python3-openssl (>= 19), python3-openssl (<< 26)"

MMDB = ("89135c55c5715294fe5655013e2bf5b114bf3af72f5c961ff599bd86df3bf576"
        "323524563537140476e1df3054ff3a56db5e613fffe87d30e6928e3203323fc5")

template_script = """#!/usr/bin/python3
import os
import sys
from re6st.cli.%s import main
if __name__ == '__main__':
    os.environ['GEOIP2_MMDB'] = "/usr/share/%s/GeoLite2-Country.mmdb"
    os.environ['PATH'] = "/etc/re6stnet/bin:" + os.environ.get(
        'PATH', '/usr/sbin:/usr/bin:/sbin:/bin')
    sys.exit(main())
"""

cli_dict = {
    'conf': 're6st-conf',
    'node': 're6stnet',
    'registry': 're6st-registry',
}

def read_check(fileobj, checksum):
    with fileobj:
        data = fileobj.read()
    if sha512(data).hexdigest() == checksum:
        return data

def main():
    repos = "re6stnet"
    def _git(*args, **kw):
        subprocess.check_call(("git", *args), **kw)
    def git_output(*args, **kw):
        return subprocess.check_output(("git", *args), cwd=repos, **kw)
    git = partial(_git, cwd=repos)

    if not os.path.exists(repos):
        _git("clone", REPOS, repos)

    git("fetch")
    git("reset", "--merge", "@{u}")

    mmdb = "GeoLite2-Country.tar.gz"
    try:
        data = read_check(open(mmdb, 'rb'), MMDB)
    except FileNotFoundError:
        data = None
    if not data:
        data = read_check(urlopen("https://shacache.nxdcdn.com/" + MMDB), MMDB)
        if not data:
            return mmdb + ": invalid checksum"
        with open(mmdb, "wb") as x:
            x.write(data)

    g = {'__file__': repos + "/re6st/version.py"}
    with open(g['__file__']) as x:
        exec(x.read(), g)
    version = "0.%(revision)s+g%(short)s" % g

    debian = []
    mtime = int(git_output("log", "-1", "--format=%ct"))
    files = git_output("ls-files",
        "daemon", "debian", "docs", "examples", "Makefile",
        text=True).splitlines()
    files.sort()
    prefix = "re6stnet-" + version
    dist_info = "/lib/re6stnet-0.%(revision)s.dist-info" % g
    def taraddtext(tarinfo, text):
        x = text.encode()
        tarinfo.size = len(x)
        wtar.addfile(tarinfo, BytesIO(x))
    def _tarfilter(tarinfo):
        tarinfo.uid = tarinfo.gid = 0
        tarinfo.uname = tarinfo.gname = "root"
        tarinfo.mtime = mtime

    def tarfilter(tarinfo):
        parent, name = os.path.split(tarinfo.name[len(prefix):])
        if parent != dist_info or name not in (
            "RECORD", "REQUESTED", "direct_url.json", "licenses",
            ):
            _tarfilter(tarinfo)
            return tarinfo
    name = f"re6stnet_{version}.tar.xz"
    with tarfile.open(name, "w:xz") as wtar:
        with tempfile.TemporaryDirectory() as tmp:
            subprocess.check_call(("pip3", "install", "--no-compile",
                                   "--no-build-isolation",
                                   "-t", tmp, "--no-deps", "."), cwd=repos)
            shutil.rmtree(tmp + "/bin")
            wtar.add(tmp, prefix + "/lib", filter=tarfilter)
        for x in files:
            if x.startswith("debian/"):
                if x != "debian/rules":
                    debian.append(x)
            else:
                wtar.add(os.path.join(repos, x), os.path.join(prefix, x),
                        filter=tarfilter)
        with tarfile.open(mmdb) as rtar:
            for tarinfo in rtar:
                x = rtar.extractfile(tarinfo)
                _tarfilter(tarinfo)
                tarinfo.name = os.path.join(prefix, tarinfo.name)
                wtar.addfile(tarinfo, x)
    print(name)

    babeld = {}
    with open('../babeld/make') as f:
        exec(f.read(), babeld)
    babeld = re.match('v(.*)-nxd', babeld['TAG'])[1]

    dsc = Deb822()
    version += f"-{PKG_VERSION}"
    dsc["Version"] = version
    def tarfilter(tarinfo):
        _tarfilter(tarinfo)
        name = tarinfo.name
        if name == "debian/control":
            with open(os.path.join(repos, name)) as x:
                s = Deb822(x); b = Deb822(x)
            s["Build-Depends"] = \
                f"debhelper-compat (= 12), python3-docutils, {PYOPENSSL}"
            s["Vcs-Git"] = \
                "https://lab.nexedi.com/nexedi/slapos.package [obs/re6st]"
            for x in "Source", "Build-Depends":
                dsc[x] = s[x]
            dsc["Architecture"] = b["Architecture"]
            b["Conflicts"] = b["Replaces"] = b["Provides"] = b["Package"]
            b["Package"] = PACKAGE
            b["Depends"] = f"{PYOPENSSL}, openvpn-re6stnet, babeld (>> 1:{
                babeld}+nxd), iproute2, openssl, python3-geoip2"
            taraddtext(tarinfo, f"{s}\n{b}")

            tarinfo.name = "debian/changelog"
            x = Changelog()
            x.new_block(
                package=s["Source"],
                version=version,
                distributions="nexedi",
                author=s["Maintainer"],
                date=format_date(mtime),
                changes=[""],
            )
            taraddtext(tarinfo, str(x))
        elif name == "debian/source/format":
            with open(os.path.join(repos, name)) as x:
                x = x.read()
            dsc["Format"] = x.rstrip()
            taraddtext(tarinfo, x)
        else:
            return tarinfo
    name = "debian.tar.xz"
    with tarfile.open(name, "w:xz") as wtar:
        wtar.add("debian", filter=tarfilter)
        for x in debian:
            wtar.add(os.path.join(repos, x), x, filter=tarfilter)
        for x in cli_dict.items():
            tarinfo = tarfile.TarInfo("debian/bin/" + x[1])
            _tarfilter(tarinfo)
            tarinfo.mode |= 0o111
            taraddtext(tarinfo, template_script % (x[0], PACKAGE))
    print(name)

    with open("re6stnet.dsc", 'w') as x:
        x.write(str(dsc))
    print(x.name)

if __name__ == '__main__':
    sys.exit(main())
