
all:
	lunzip/build-scripts/10tarball_directory.sh
	lunzip/build-scripts/20obs.sh
clean:
	rm -rf _tarballs/lunzip_1-1/
	rm -rf home:oph.nxd/lunzip/*

clean_all:
	rm -rf _tarballs
	rm -rf home:*

.PHONY: all clean clean_all
