---

  - name: SSH: Allow root
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin (.*)" line="PermitRootLogin yes" state=present
    notify: [ 'Reload sshd' ]

  - name: SSH: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication (.*)" line="PasswordAuthentication no" state=present
    notify: [ 'Reload sshd' ]
