---
  - name: SSH PermitRootLogin count
    command:
      argv:
        - egrep
        - -c
        - ^PermitRootLogin prohibit-password$
        - /etc/ssh/sshd_config
    ignore_errors: true
    register: permitrootlogincount

  - name: SSH PasswordAuthentication count
    command:
      argv:
        - egrep
        - -c
        - ^PasswordAuthentication no$
        - /etc/ssh/sshd_config
    ignore_errors: true
    register: passwordauthenticatoincount

  - name: SSH PermitRootLogin cleanup
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "PermitRootLogin"
      state: absent
      validate: sshd -t -f %s
    when: permitrootlogincount.stdout != "1"
    notify: [ 'Reload sshd' ]

  - name: SSH PermitRootLogin setup
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin prohibit-password$"
      line: "PermitRootLogin prohibit-password"
      state: present
      validate: sshd -t -f %s
    notify: [ 'Reload sshd' ]

  - name: SSH PasswordAuthentication cleanup
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "PasswordAuthentication"
      state: absent
      validate: sshd -t -f %s
    when: passwordauthenticatoincount.stdout != "1"
    notify: [ 'Reload sshd' ]

  - name: SSH PasswordAuthentication setup
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication no$"
      line: "PasswordAuthentication no"
      state: present
      validate: sshd -t -f %s
    notify: [ 'Reload sshd' ]
