---
  - name: Get hostname
    shell: hostname
    register: hostname

  - name: Check hostname
    debug: var=hostname

  - name: Install rm-tmp-lte script
    copy: src=rm-tmp-lte dest={{ install_folder }} owner=root mode=770

  - name: Give permission to slapuser to remove tmp files owned by other slapuser
    copy: src=slapuser-rm-tmp dest=/etc/sudoers.d owner=root mode=440

  - name: Init SDR
    script: init-sdr.sh

  - name: Configure re6st
    script: configure-re6st.sh

  - name: Configure /etc/network/interfaces
    copy: src=interfaces dest=/etc/network/interfaces owner=root mode=644

  - name: Configure dhcp timeout
    lineinfile: dest=/etc/dhcp/dhclient.conf regexp="^timeout (.*)" line="timeout 15" state=present

  - name: Configure ssh
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin (.*)" line="PermitRootLogin yes" state=present

  - name: Configure ssh
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication (.*)" line="PasswordAuthentication yes" state=present

  - name: Configure slapos
    script: configure-slapos.py

  - name: Create .amarisoft directory for SR
    file: path=/opt/amarisoft/.amarisoft state=directory

  - name: Copy keys for SR
    copy: src=/root/.amarisoft dest=/opt/amarisoft owner=root mode=644

  - name: Add kernel parameter
    script: configure-grub.sh
