---
  - name: Configure unbound
    copy: src="unbound.conf" dest="/etc/unbound/unbound.conf" mode=0644 owner=root group=root
    notify: [ 'Restart unbound' ]
  - name: Configure systemd-resolved
    copy: src="resolved.conf" dest="/etc/systemd/resolved.conf" mode=0644 owner=root group=root
    notify: [ 'Restart systemd-resolved' ]
  - name: Assure unbound
    ansible.builtin.systemd_service:
      enabled: true
      masked: false
      name: unbound
  - name: Assure systemd-resolved
    ansible.builtin.systemd_service:
      enabled: true
      masked: false
      name: systemd-resolved
