---
dependencies:
  - { role: ntp }
  - { role: package, package_name: lm-sensors, package_state: latest }
  - { role: package, package_name: wget, package_state: latest }
  - { role: package, package_name: openssl, package_state: latest }
  - { role: package, package_name: ca-certificates, package_state: latest }
  - { role: package, package_name: openssh-server, package_state: latest }
  - { role: package, package_name: mosh, package_state: latest }
  - { role: package, package_name: strace, package_state: latest }
  - { role: package, package_name: htop, package_state: latest }
  - { role: package, package_name: ioping, package_state: latest }
  - { role: package, package_name: fuse, package_state: latest }
  - { role: package, package_name: exim4-base, package_state: absent }
  - { role: package, package_name: slapos-node, package_state: latest }
  - { role: package, package_name: re6st-node, package_state: present }
  - { role: upgrade-apt, when: is_debian_or_ubuntu }
  - { role: re6stnet-ensure-running }
  - { role: etckeeper }
  - { role: vifib-team-ssh-key }
  - { role: vifib-server }
  - { role: rsyslogd }
  - { role: sysstat }
  - { role: vifib-kernel, when: upgrade_kernel | default(False) == True }
  - { role: cpu-scaling-governor, value: performance }
  - { role: fstrim }
