- name: Install Python
  apt:
    name: python
    state: present

- name: Install pip
  apt:
    name: python-pip
    state: present

- name: Install i2c-tools
  apt:
    name: i2c-tools
    state: present

- name: Install Python package bme280
  pip:
    name: bme280

- name: Install python-smbus
  apt:
    name: python-smbus
    state: present

- name: Solve python template to read sensor
  template:
    src: read_bme280.j2
    dest: /usr/local/bin/read_bme280.py
