- name: Install apt package dependencies
  apt:
    pkg:
      - python
      - python-pip
      - i2c-tools
      - python-smbus
    state: present


- name: Install setuptools
  pip:
    name: setuptools

- name: Install bme280
  pip:
    name: bme280

- name: Solve python template to read sensor
  template:
    src: read_bme280.j2
    dest: /usr/local/bin/custom_read_bme280.py

- name: Add access sensor permission for slapsoft
  copy:
    src: 60-i2c-tools.rules
    dest: /etc/udev/rules.d/60-i2c-tools.rules
    owner: root
