---
  - name: Get current LTE version
    stat: path=/opt/amarisoft/lte
    register: lte_version

  - name: Get hostname
    shell: hostname
    register: hostname

  - name: Check new LTE
    debug: msg="New amarisoft LTE available"
    when: lte_version.stat.lnk_target is not search(current_lte_version)

  - name: Check hostname
    debug: var=hostname
