## PACKAGES
mca_name: mca--static
fluentbit_name: fluent-bit
mca_path: /opt/{{mca_name}}
flb_path: /opt/{{fluentbit_name}}

## WENDELIN CONFIGURATION
wendelin_url: "{{ lookup('env', 'ANSIBLE_wendelin_url') }}"
wendelin_pwd: "{{ lookup('env', 'ANSIBLE_wendelin_pwd') }}"
wendelin_reference: "{{ lookup('env', 'ANSIBLE_wendelin_reference') }}"
packages_to_scan: "{{ lookup('env', 'ANSIBLE_packages_to_scan') }}"

## OTHER
conf_regex: s|%WENDELIN_URL%|{{wendelin_url}}|g;s|%WENDELIN_PWD%|{{wendelin_pwd}}|g;s|%WENDELIN_REFERENCE%|{{wendelin_reference}}|g

binary: "{{mca_path}}/bin/metadata-collect-agent"
flb: "{{flb_path}}/bin/fluent-bit"
flb_plugin: "{{mca_path}}/lib/libfluentbit_wendelin.so"
flb_conf: "{{mca_path}}/etc/flb.conf"
log: /var/log/metadata_collect.log

sucess_string: "\n(success string:) Build successful, connect to:\n"
