---
  - name: Install kernel 4.6 on debian 8.0
    apt: name=linux-image-4.6.0-0.bpo.1-amd64  state=latest default_release=jessie-backports update_cache=yes
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"        


