---

  - name: Install kernel 4.9 on debian 9.0
    apt: name=linux-image-4.9.0-5-amd64  state=latest update_cache=yes
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"

  - name: Install Debian jessie-backports repository
    lineinfile: dest='/etc/apt/sources.list' line='deb http://ftp.debian.org/debian jessie-backports main' state=present
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"

  - name: Install kernel 4.9 on debian 8.0
    apt: name=linux-image-4.9.0-0.bpo.5-amd64  state=latest default_release=jessie-backports update_cache=yes
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"        

  - name: Install Debian jessie repository on debian 7
    lineinfile:
      dest: '/etc/apt/sources.list'
      line: "{{item.line}}"
      state: present
    with_items:
      - {line: "deb http://deb.debian.org/debian jessie main"}
      - {line: "deb-src http://deb.debian.org/debian jessie main"}
      - {line: "deb http://security.debian.org/ jessie/updates main contrib non-free"}
      - {line: "deb-src http://security.debian.org/ jessie/updates main contrib non-free"}
      - {line: "deb http://ftp.debian.org/debian jessie-backports main"}
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"

  - name: Dist upgrade debian 7 to debian 8
    apt: upgrade=dist update_cache=yes
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"
