- name: Caddy frontend supply 
  shell: slapos supply {{ frontend_software_release_url }} {{ computer_id }}
  when : slapos_cfg.stat.exists == True
  args: 
    creates: /opt/supply_check_file

- name : requesting Caddy frontend istance
  shell: echo "request('{{ frontend_software_release_url }}', '{{ frontend_instance_name }}',filter_kw={'computer_guid':'{{ computer_id}}'}, partition_parameter_kw={'-sla-1-computer_guid':'{{ computer_id }}','domain':'{{ domain_name }}','public-ipv4':'{{ ansible_default_ipv4.address }}',}, software_type='custom-personal',)" | slapos console
  when: supply_is_done == True
