  - name: Install repository (with DEB822)
    ansible.builtin.deb822_repository:
      name: obs_VIFIBnexedi
      types: [deb]
      uris: "{{ url }}"
      suites: ./
      signed_by: "{{ url }}/Release.key"
      state: present
      enabled: true
    vars:
      url: "{{ base_open_build_url }}{{
        'xUbuntu_' + ansible_distribution_version
        if ansible_distribution == 'Ubuntu' else
        ansible_distribution + '_' + ansible_distribution_major_version }}"
