
  - name: Allow release-info to change for APT repositories
    command: apt-get update -y --allow-releaseinfo-change
    when: ansible_os_family == "Debian" or ansible_os_family == "Linuxmint"

  - name: Install gpg using apt
    apt: name=gpg state=present
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

