  - name: Allow release-info to change for APT repositories
    command: apt-get update -y --allow-releaseinfo-change
    when: (ansible_distribution == "Debian" and ansible_ditribution_major_version|int > 9) or
          (ansible_ditribution == "Ubuntu" and ansible_ditribution_major_version|int > 18)

  - name: Install gpg using apt
    apt:
      name:
      - gpg
      state: present
    when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"

