---
  - name: Remove legacy repositories from git.erp5.org
    apt_key: id=1A716324 state=absent
    when: ansible_distribution == "Debian" and not (rina or "/usr/bin/ipcm"|is_file)

  - name: Remove {{ base_open_build_url }} key (and add later) on every upgrade, as expiration date is quite short (2 months).
    apt_key: id=94A63987 state=absent
    when: ansible_distribution == "Debian"

  - file: path=/etc/apt/sources.list.d/re6stnet.list state=absent
    when: ansible_distribution == "Debian"

  - name: Install Debian {{ ansible_distribution_major_version }} repository key
    apt_key: url={{ base_open_build_url }}/Debian_{{ ansible_distribution_major_version }}.0/Release.key state=present
    when: ansible_distribution == "Debian"

  - name: Install Debian {{ ansible_distribution_major_version }} repository
    apt_repository: repo='deb {{ base_open_build_url }}/Debian_{{ ansible_distribution_major_version }}.0/ ./' state=present
    when: ansible_distribution == "Debian"

  - name: Install Ubuntu {{ ansible_distribution_version }} repository key
    apt_key: url={{ base_open_build_url }}/xUbuntu_14.04/Release.key state=present
    when: ansible_distribution == "Ubuntu"

  - name: Install Ubuntu {{ ansible_distribution_version }} repository
    apt_repository: repo='deb {{ base_open_build_url }}/xUbuntu_{{ ansible_distribution_version }}/ ./' state=present
    when: ansible_distribution == "Ubuntu" 

  - name: Install Ubuntu 14.04 repository key (Linuxmint 17.2)
    apt_key: url={{ base_open_build_url }}/xUbuntu_14.04/Release.key state=present
    when: ansible_distribution == "Linuxmint" and ansible_distribution_version == "17.2"

  - name: Install Ubuntu 14.04 repository (Linuxmint 17.2)
    apt_repository: repo='deb {{ base_open_build_url }}/xUbuntu_14.04/ ./' state=present
    when: ansible_distribution == "Linuxmint" and ansible_distribution_version == "17.2"

  - name: Install CentOS 7 Repository
    get_url: url=http://download.opensuse.org/repositories/home:/VIFIBnexedi/CentOS_7/home:VIFIBnexedi.repo dest=/etc/yum.repos.d/slapos.repo mode=0440
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: Install CentOS 7 RPM Key
    rpm_key: state=present key=http://download.opensuse.org/repositories/home:/VIFIBnexedi/CentOS_7/repodata/repomd.xml.key
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

  - name: Install CentOS 6 Repository
    get_url: url=http://download.opensuse.org/repositories/home:/VIFIBnexedi/CentOS_CentOS-6/home:VIFIBnexedi.repo dest=/etc/yum.repos.d/slapos.repo mode=0440
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

  - name: Install CentOS 6 RPM Key
    rpm_key: state=present key=http://download.opensuse.org/repositories/home:/VIFIBnexedi/CentOS_CentOS-6/repodata/repomd.xml.key
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

