#!/bin/sh
### BEGIN INIT INFO
# Provides:          Init SDR
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Init SDR
### END INIT INFO

case "$1" in
  start)
    cd /root/trx_sdr/kernel;
    make clean;
    bash init.sh 2>> /opt/amarisoft/init-sdr.log >> /opt/amarisoft/init-sdr.log
    /opt/amarisoft/v2022-07-29/lteenb-linux-2022-07-29/lte_init.sh 2>> /opt/amarisoft/init-sdr.log >> /opt/amarisoft/init-sdr.log
    ;;
  *)
    true
esac
