#!/usr/bin/python3
import os, re, subprocess, sys, tarfile
from functools import partial
from io import BytesIO
from urllib.request import urlopen
from debian.changelog import format_date, Changelog
from debian.deb822 import Deb822

TAG = "v1.13.1-nxd1"
DEBIAN_VERSION = "1.13.1+ds-1"
SOURCE_VERSION = TAG[1:].replace("-nxd", "+nxd")
VERSION = SOURCE_VERSION + "-1"
EPOCH = 1

MAINTAINER = "Julien Muchembled <jm@nexedi.com>"
CHANGES = """
  * Nexedi fork for re6stnet.
"""

REPOS = "https://lab.nexedi.com/nexedi/babeld"


def main():
    repos = "babeld"
    def _git(*args, **kw):
        subprocess.check_call(("git", *args), **kw)
    def git_output(*args, **kw):
        return subprocess.check_output(("git", *args), cwd=repos, **kw)
    git = partial(_git, cwd=repos)

    if not os.path.exists(os.path.join(repos, "rfc6234", ".git")):
        _git("clone", "-c", "submodule.recurse=true", REPOS, repos)
        git("submodule", "update", "--init", "rfc6234")

    git("fetch")
    git("reset", "--merge", "refs/tags/" + TAG)
    mtime = int(git_output("log", "-1", "--format=%ct"))
    files = git_output("ls-files", "-z", "--recurse-submodules",
                       ).rstrip(b'\0').split(b'\0')
    files.sort()
    prefix = "babeld-" + SOURCE_VERSION
    def tarfilter(tarinfo):
        tarinfo.uid = tarinfo.gid = 0
        tarinfo.uname = tarinfo.gname = "root"
        tarinfo.mtime = mtime
        return tarinfo
    with tarfile.open(f"babeld_{SOURCE_VERSION}.tar.xz", "w:xz") as wtar:
        for x in files:
            x = x.decode()
            wtar.add(os.path.join(repos, x), os.path.join(prefix, x),
                     filter=tarfilter)

    d = Deb822()
    d["Version"] = f'{EPOCH}:{VERSION}'
    with urlopen("https://deb.debian.org/debian/pool/main/b/babeld/"
                 f"babeld_{DEBIAN_VERSION}.debian.tar.xz") as x, \
         tarfile.open(mode='r|xz', fileobj=x) as rtar, \
         tarfile.open("debian.tar.xz", "w:xz") as wtar:
        for tarinfo in rtar:
            fileobj = rtar.extractfile(tarinfo)
            while True: # not a loop
                if tarinfo.name == "debian/changelog":
                    dch = Changelog(fileobj)
                    dch.new_block(
                        package=dch.package,
                        version=d["Version"],
                        distributions="nexedi",
                        author=MAINTAINER,
                        date=format_date(mtime),
                        changes=[CHANGES],
                    )
                    x = str(dch).encode()
                elif tarinfo.name == "debian/control":
                    s = Deb822(fileobj); b = Deb822(fileobj)
                    s["Build-Depends"] = "debhelper-compat (= 12), libb2-dev"
                    s["Maintainer"] = MAINTAINER
                    s["Homepage"] = REPOS
                    del s["Uploaders"], s["Vcs-Browser"]
                    s["Vcs-Git"] = "https://lab.nexedi.com/nexedi/slapos.package [obs/babeld]"
                    x = f"{s}\n{b}".encode()
                elif tarinfo.name == "debian/patches/0001-Allow-using-sha2-and-blake2-system-libaries.patch":
                    # Fix conflicts with Nexedi changes in Makefile.
                    x = re.sub(rb'(\n[-+]       )(hmac)(\.[co])',
                               rb'\1ctl\3 \2\3', fileobj.read())
                else:
                    if tarinfo.name == "debian/source/format":
                        fileobj = BytesIO(fileobj.read())
                        d["Format"] = fileobj.getvalue().decode().strip()
                    break
                tarinfo.mtime = mtime
                tarinfo.size = len(x)
                fileobj = BytesIO(x)
                break
            wtar.addfile(tarinfo, fileobj=fileobj)

    for x in "Source", "Build-Depends":
        d[x] = s[x]
    d["Architecture"] = b["Architecture"]
    with open("babeld.dsc", 'w') as x:
        x.write(str(d))

if __name__ == '__main__':
    sys.exit(main())
