#!/bin/bash
mkdir -p /etc/sudoers.d
PARTITION_AMOUNT="$(sed -n 's/partition_amount = \(.*\)/\1/gp' /etc/opt/slapos/slapos.cfg)"

add_line() {
  echo "Configuring /etc/sudoers.d/slapuser-$1..."/
  for i in $(seq 0 $(($PARTITION_AMOUNT-1))); do
    echo "slapuser$i ALL=NOPASSWD:$2" >> slapuser-20241205-$1
  done
  mv slapuser-20241205-$1 /etc/sudoers.d/
  chmod 440 /etc/sudoers.d/slapuser-20241205-$1
}

add_line lteue "$1/v$2/ue/lteue"
