#!/bin/bash
mkdir -p /etc/sudoers.d
COMMAND_LIST=("init-ue")
PARTITION_AMOUNT="$(sed -n 's/partition_amount = \(.*\)/\1/gp' /etc/opt/slapos/slapos.cfg)"
for c in "${COMMAND_LIST[@]}"; do
  SLAPUSER_LINES="$(cat /etc/sudoers.d/slapuser-$c 2> /dev/null | wc -l)"
  if [ "$SLAPUSER_LINES" != "$PARTITION_AMOUNT" ]; then
    echo "Configuring /etc/sudoers.d/slapuser-$c..."
    for i in $(seq 0 $(($PARTITION_AMOUNT-1))); do
      echo "slapuser$i ALL=NOPASSWD:/opt/amarisoft/$c" >> slapuser-$c
    done
    mv slapuser-$c /etc/sudoers.d/
    chmod 440 /etc/sudoers.d/slapuser-$c
  fi
done
c="lteue"
SLAPUSER_LINES="$(cat /etc/sudoers.d/slapuser-$c 2> /dev/null | wc -l)"
AMARISOFT_PATH="/opt/amarisoft/$(ls -1 /opt/amarisoft | grep "^v[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$" | sort | tail -n1)"
echo "Configuring /etc/sudoers.d/slapuser-$c..."
echo > slapuser-$c
for i in $(seq 0 $(($PARTITION_AMOUNT-1))); do
  echo "slapuser$i ALL=NOPASSWD:$AMARISOFT_PATH/ue/lteue" >> slapuser-$c
done
mv slapuser-$c /etc/sudoers.d/
chmod 440 /etc/sudoers.d/slapuser-$c
